name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Set CI environment variable to false
        run: echo "CI=false" >> $GITHUB_ENV
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies for outermost directory
        run: npm install
        
      - name: Install dependencies for frontend
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Run tests for frontend
        run: npm test
        working-directory: frontend

      - name: Install dependencies for backend
        run: npm ci
        working-directory: backend

      - name: Run tests for backend
        run: npm run test
        working-directory: backend

# TODO: deployment
